server:
   port: 9192
   
spring:
  
  zipkin:
    base-url: http://localhost:9411/
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    
  jpa:
   properties:
      hibernate:
       dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      
  application:
    name: order-service

logging:  file:    name: C:\Users\Dhêimy Silva\Documents\logs\microservice.log